@startjson
{
  "Nodes": [{ 
  "nodeId" : { "sensors" : [
{"sensor type": "humidity",
 "measurement interval(seconds)" : "60",
 "measurements" : [{ "measure value" : "value", "measure time": "time"},{ "measure value" : "value", "measure time": "time"}]
},
{"sensor type": "temp",
 "measurement interval(seconds)" : "60",
 "measurements" : [{ "measure value" : "value", "measure time": "time"},{ "measure value" : "value", "measure time": "time"}]
}
],
                  "firmware version" : "version",
                  "nickname" : "nick" }
  },
{ 
  "nodeId2" : { "sensors" : [
{"sensor type": "sensor",
 "measurement interval(seconds)" : "600",
 "measurements" : []
},
{"sensor type": "sensor",
 "measurement interval(seconds)" : "60",
 "measurements" : []
}
],
                  "firmware version" : "version",
                  "nickname" : "nick" }
  }
],
  "Mesh Network": {
     "node1" : "nodeId1",
     "nodeId2" : "nodeid2",
     "nodeId3" : "nodeid3"
  },
  "Nodes Nicknames": [{"nodeId" : "nickname"},{"nodeId2" : "nickname"},{"nodeId3" : "nickname"}],
  "Nodes changes": [{"nodeId": "ID" , "node sensor": "sensor", "time interval": "time"},{"nodeId2": "ID2" , "node sensor": "sensor", "time interval": "time"}]
}
@endjson